# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: federalist-landing-page-template

email: federalist-inquiries@gsa.gov

# this means to ignore newlines until "baseurl:"
description: ''

# the subpath of your site, e.g. /blog
baseurl: ''

# the base hostname & protocol for your site
url: ''

# Replace "18f" with your org name
org_name: 18F

# Replace "federalist-modern-team-template" with your repo name
repo_name: federalist-landing-page-template

twitter_username: 18F
github_username:  18F

# scripts to load on all pages
scripts: []


# Pop-Up —— appears once every 60mins on the site.
# Options:
popup: previews-only                 # pop-up displayed across Federalist previews
# popup: all-branches                  # pop-up displayed across all branches
popup_copy: 'This site is currently in development by the Technology Transformation Service at the General Services Administration.'

# popup: password                        # (soft) pass wall displayed across all branches
# popup_pass: 'freedom'                  # Password for when "popup: password" is used
                                       # THIS IS NOT A MEANS OF SECURING INFORMATION



# Build settings
markdown: kramdown

# Exlude files from being present in the build site
exclude:
- ".gitignore"
- Gemfile
- Gemfile.lock
- README.md
- LICENSE
- package.json
- node_modules
- README.md
